environment:
  matrix:
  - ARTIFACT_NAME: v8js_vc14_php-7.1_%Platform%_ts.zip
    OUTDIR: Release_TS
    V8_ASSETS: V8-5.8.283.31-%Platform%.zip
    PHP_VERSION: 7.1.4
  - ARTIFACT_NAME: v8js_vc14_php-7.1_%Platform%_nts.zip
    OUTDIR: Release
    CONFIGURE_EXTRA: --disable-zts
    V8_ASSETS: V8-5.8.283.31-%Platform%.zip
    PHP_VERSION: 7.1.4
  - ARTIFACT_NAME: v8js_vc14_php-7.0_%Platform%_ts.zip
    OUTDIR: Release_TS
    V8_ASSETS: V8-5.8.283.31-%Platform%.zip
    PHP_VERSION: 7.0.18
  - ARTIFACT_NAME: v8js_vc14_php-7.0_%Platform%_nts.zip
    OUTDIR: Release
    CONFIGURE_EXTRA: --disable-zts
    V8_ASSETS: V8-5.8.283.31-%Platform%.zip
    PHP_VERSION: 7.0.18

  PHP_SDK: c:\projects\php-sdk

os: Windows Server 2012
clone_folder: c:\projects\php-sdk\v8js-ci\vc14\%Platform%\php\ext\v8js

platform:
  - x64
  - x86

install:
  - cd %PHP_SDK%
  - curl -fSL -o php-sdk-binary-tools-20110915.zip "http://windows.php.net/downloads/php-sdk/php-sdk-binary-tools-20110915.zip"
  - 7z.exe x php-sdk-binary-tools-20110915.zip
  - call bin\phpsdk_setvars.bat
  - call bin\phpsdk_buildtree.bat v8js-ci
  - cd v8js-ci\vc14\%Platform%
  - md deps
  - cd deps
  - curl -fSL -o %V8_ASSETS% "https://s3.amazonaws.com/win-phpv8/%V8_ASSETS%"
  - 7z.exe x %V8_ASSETS%
  - cd ..
  - curl -fSL -o "php-%PHP_VERSION%.tar.gz" "http://us1.php.net/distributions/php-%PHP_VERSION%.tar.gz"
  - ren php php-%PHP_VERSION%
  - 7z.exe x php-%PHP_VERSION%.tar.gz -y
  - 7z.exe x php-%PHP_VERSION%.tar -y | find /v "Extracting"
  - cd php-%PHP_VERSION%
  - IF "%Platform%" == "x64" SET OUTDIR=x64\%OUTDIR%
  - mkdir %OUTDIR%
  - move ..\deps\bin\*.dll %OUTDIR%\
  - move ..\deps\bin\icudtl.dat %OUTDIR%\

build_script:
  - ps: >-
      If ($env:Platform -Match "x86") {
        $env:VCVARS_PLATFORM="x86"
        $env:ENV_PLATFORM="x86"
      } Else {
        $env:VCVARS_PLATFORM="amd64"
        $env:ENV_PLATFORM="x64"
      }
  - call "%VS140COMNTOOLS%\..\..\VC\vcvarsall.bat" %VCVARS_PLATFORM%
  - echo Building PHP [%PHP_VERSION%]
  - '%PHP_SDK%\bin\phpsdk_setvars'
  - buildconf
  - configure --disable-all --enable-cli --with-v8js %CONFIGURE_EXTRA%
  - nmake

after_build:
  - cd %OUTDIR%
  - 7z a %ARTIFACT_NAME% icudtl.dat icu*.dll v8.dll php_v8js.dll
  - ps: Push-AppveyorArtifact $env:ARTIFACT_NAME

test_script:
  - cd c:\projects\php-sdk\v8js-ci\vc14\%Platform%\php-%PHP_VERSION%
  - set NO_INTERACTION=1
  - set TEST_PHP_JUNIT=junit.xml
  - set REPORT_EXIT_STATUS=1
  - "%OUTDIR%\\php.exe run-tests.php -p %OUTDIR%\\php.exe ext/v8js/tests/ -d v8js.icudtl_dat_path=%OUTDIR%/icudtl.dat -d extension=php_v8js.dll -d extension_dir=%OUTDIR%\\"

on_finish:
  - cd c:\projects\php-sdk\v8js-ci\vc14\%Platform%\php-%PHP_VERSION%
  - ps: |
      # upload results to AppVeyor
      $wc = New-Object 'System.Net.WebClient'
      $wc.UploadFile("https://ci.appveyor.com/api/testresults/junit/$($env:APPVEYOR_JOB_ID)", (Resolve-Path .\junit.xml))

deploy:
  provider: S3
  access_key_id: AKIAJBJLBBZPMYOGVKEA
  secret_access_key:
    secure: N+jqdcvCOzqfrwL7ClIvcd9TkmQe9dghJwZMjLYtv7syVW5c4EU9YrqUbUUGmZ04
  bucket: win-phpv8
  set_public: true
  artifact: "*.zip"
  on:
    branch: php7

